### ISSUE TITLE
Could not connect to server: Connection refused

### ISSUE THREAD

**Issue by peteruithoven** [prashant0079/metabolic_assignment#1] opened 2021-09-05 15:39 UTC
Hi @prashant0079, 

I'm running into the following issue when running the `docker-compose run app alembic revision` step.

```
$ docker-compose run app alembic revision --autogenerate -m "1st Schema Migration"
Starting 8d0b562baeb7_postgresql_db ... done
Traceback (most recent call last):
    # Removed some lines
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "db" (172.21.0.2) and accepting
	TCP/IP connections on port 5433?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  # Removed some lines
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "db" (172.21.0.2) and accepting
	TCP/IP connections on port 5433?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

The project does seem to start correctly:
```
$ docker-compose up   
Removing postgresql_db
Starting 8d0b562baeb7_postgresql_db ... done
Starting pgadmin                    ... done
Recreating app                      ... done
Attaching to 8d0b562baeb7_postgresql_db, pgadmin, app
8d0b562baeb7_postgresql_db | 
8d0b562baeb7_postgresql_db | PostgreSQL Database directory appears to contain a database; Skipping initialization
8d0b562baeb7_postgresql_db | 
8d0b562baeb7_postgresql_db | 2021-09-04 23:40:20.016 UTC [1] LOG:  starting PostgreSQL 13.4 (Debian 13.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
8d0b562baeb7_postgresql_db | 2021-09-04 23:40:20.017 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
8d0b562baeb7_postgresql_db | 2021-09-04 23:40:20.017 UTC [1] LOG:  listening on IPv6 address "::", port 5432
8d0b562baeb7_postgresql_db | 2021-09-04 23:40:20.038 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
8d0b562baeb7_postgresql_db | 2021-09-04 23:40:20.058 UTC [26] LOG:  database system was shut down at 2021-09-04 23:39:42 UTC
8d0b562baeb7_postgresql_db | 2021-09-04 23:40:20.068 UTC [1] LOG:  database system is ready to accept connections
app        | INFO:     Will watch for changes in these directories: ['/app']
app        | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
app        | INFO:     Started reloader process [1] using statreload
app        | INFO:     Started server process [9]
app        | INFO:     Waiting for application startup.
app        | INFO:     Application startup complete.
pgadmin    | [2021-09-04 23:40:27 +0000] [1] [INFO] Starting gunicorn 20.1.0
pgadmin    | [2021-09-04 23:40:27 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
pgadmin    | [2021-09-04 23:40:27 +0000] [1] [INFO] Using worker: gthread
pgadmin    | [2021-09-04 23:40:27 +0000] [82] [INFO] Booting worker with pid: 82
```

I did have to change the version of the compose file from 3.8 to 3.3 because I'm probably running an older Docker version. 
I've set `DB_PORT=5433` because I'm already running PostgreSQL locally. 
I'm one of the front-enders at Metabolic, so I'm probably lacking some relevant knowledge.

**Comment by prashant0079** [comment] 2021-09-05 18:20
Hello Peter,

Db is being used as a service running as a docker container. You cannot make a reference to your **postgres** installation as the project references to the **postgres container** already running inside your docker. I have made some changes to the .env.template. Please don't change the **DB_PORT** and **DB_SERVICE**. And follow the rest of instructions in the **.env.template**. The project will run fine :)

Let me know if still the issue persists.

**Comment by prashant0079** [comment] 2021-09-05 20:17
Good news @peteruithoven, I was able to pin point the exact issue to the native postgres container. Even though you were changing the DB_PORT it didn't reflect on the db service.
Therefore I had to make the following changes to the docker compose and the issue is fixed in the following [PR](https://github.com/prashant0079/metabolic_assignment/pull/2). Now you can run this on any port.

Since you have run the migrations command already, I'll also request you to delete all the files in the **migration/versions/**
Don't delete the folder altogether. It will run fine.

**Comment by peteruithoven** [comment] 2021-09-05 20:22
> Db is being used as a service running as a docker container. You cannot make a reference to your postgres installation as the project references to the postgres container already running inside your docker.

I didn't try to. I changed the DB_PORT to avoid using my local postgres. 

> Please don't change the DB_PORT and DB_SERVICE. And follow the rest of instructions in the .env.template. 

`.env.template` just said "DB_PORT for eg. 5432". 

But, you're right, even with the alternative DP_PORT it does seem to work now. I've got the REST API working. That was a quick fix.

**Closed as completed** 2021-09-05 20:26 UTC
